# https://docs.github.com/en/actions/guides/publishing-docker-images

name: Publish Docker images

on:
  workflow_dispatch: # manually triggered
  push:
    branches: [ latest, stable, 24.05 ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Extract branch name
        uses: vazco/github-actions-branch-name@v1
        id: branch

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: dalibo/pandocker

      - name: Build and push the `extra` image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          target: extra
          tags: dalibo/pandocker:${{ steps.branch.outputs.branch_name }}

      - name: Build and push the `full` image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          target: full
          tags: dalibo/pandocker:${{ steps.branch.outputs.branch_name }}-full